### PR TITLE
Added CoC team members with contact info and images

### PR DESCRIPTION
**Pull request by marcduiker**

### CODE REVIEW

**Review by mikhailshilkov — APPROVED** [review]
Preview: https://5e14fc59956989000b9c5ae0--vigorous-wescoff-fe2849.netlify.com/#coc

LGTM.

**Comment by mikhailshilkov** [comment]
You could make it driven from data in the config file similar to e.g. date list, but not sure if it's worth the effort.

**Comment by marcduiker** [comment]
Didn't seem the effort would be worth it. I think the preview looks good. Can you merge it?

**Comment by mikhailshilkov** [comment]
I'll improve it when I get bored with other stuff :)

**Pull request merged**
